# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170806_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='pubdate',
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=140, unique_for_date='pubdate'),
        ),
    ]
