# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-14 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20170821_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=None),
        ),
    ]
