# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20170811_0006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='_content_rendered',
            new_name='_body_rendered',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='body',
        ),
    ]
