# pylint: disable=C0103
# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-21 14:05
from __future__ import unicode_literals

from django.db import migrations
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20170821_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='_body_rendered',
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=django_markdown.models.MarkdownField(),
        ),
    ]
